### ISSUE TITLE
Option to upload file by path

### ISSUE THREAD

**Issue by adscib** [jowilf/sqlalchemy-file#54]
Currently, the library only supports uploading files [by stream](https://github.com/jowilf/sqlalchemy-file/blob/2be8492c9023f31919b4bae431c72b634c22352a/sqlalchemy_file/storage.py#L105). Would it be possible to add an option to upload by file path? That's [supported in libcloud](https://github.com/apache/libcloud/blob/d163f9ba5938aff7d23dec72fa549a482f6836c7/libcloud/storage/base.py#L201), so I suppose it wouldn't be too difficult. I'm happy to make a PR.

**Comment by jowilf** [comment]
Can you explain me the necessity of this function? [File](https://jowilf.github.io/sqlalchemy-file/api/file/#sqlalchemy_file.file.File) doesn't support file path

**Comment by adscib** [comment]
I'm storing large files that can't be fully loaded in memory and it saves me the headache of managing stream life cycles. I'm not sure whether it impacts performance. The other advantage is that File holds a local path to the underlying file even before it's committed.

I was able to get this to work in my fork by adding and extra argument to File.

**Comment by jowilf** [comment]
Hi @adscib, Would you be interested in submitting a PR?

**Comment by adscib** [comment]
For sure. See #87.
